// templates/vue2/demo/less/components/page-header/page-header.vue
<template>
  <div class="header-wrap">
    <header class="container">
      <div class="pull-left brand">Quick start</div>
      <div class="pull-right link">
        <a href="https://github.com/18616392776/quick-start-cli">Github</a>
      </div>
    </header>
  </div>
</template>

<style lang="less" rel="stylesheet/less" scoped>
  @import "../../assets/less/varibles.less";

  .header-wrap {
    background-color: $color-default;
    height: 100%;
    padding-top: 5px;
    box-sizing: border-box;
  }

  .brand {
    color: #fff;
    font-size: 36px;

  }

  .link {
    padding-top: 12px;
    a {
      text-decoration: none;
      padding: 5px 10px;
      background-color: $color-primary;
      border-radius: 3px;
      color: #fff;
      transition: background-color .3s;
      &:hover {
        background-color: $color-primary - 50;
      }
    }
  }

</style>

// templates/react/demo/less/components/page-header/page-header.jsx
import React from 'react';
import cssModules from 'react-css-modules';
import styles from './page-header.less';

function pageHeader() {
  return (
    <div styleName="header-wrap">
      <header className="container">
        <div className="pull-left" styleName="brand">Quick start</div>
        <div className="pull-right" styleName="link">
          <a href="https://github.com/18616392776/quick-start-cli">Github</a>
        </div>
      </header>
    </div>
  );
}

export default cssModules(pageHeader, styles);
