// templates/vue/demo/stylus/views/app.vue
<template>
  <div class="page-wrap">
    <div class="page">
      <div class="header">
        <PageHeader></PageHeader>
      </div>
      <div class="page-content">
        <router-view></router-view>
      </div>
    </div>
    <div class="footer">
      <PageFooter></PageFooter>
    </div>
  </div>
</template>

<script>
  import PageHeaderComponent from '../components/page-header/page-header'
  import PageFooterComponent from '../components/page-footer/page-footer'
  export default {
    components: {
      PageHeader: PageHeaderComponent,
      PageFooter: PageFooterComponent
    }
  }
</script>

// templates/react/typescript/demo/less/app.tsx
import * as React from 'react';
import { Component } from 'react';
import { render } from 'react-dom';
import { Route, BrowserRouter } from 'react-router-dom';
import 'normalize.css';
import './assets/less/index.less';

import PageHeader from './components/page-header/page-header';
import PageFooter from './components/page-footer/page-footer';
import Home from './views/home/home';

class App extends Component {
    render() {
        return (
            <div className="page-wrap">
                <div className="page">
                    <div className="header">
                        <PageHeader/>
                    </div>
                    <div className="page-content">
                        <BrowserRouter>
                            <Route path="/" component={Home}/>
                        </BrowserRouter>
                    </div>
                </div>
                <div className="footer">
                    <PageFooter/>
                </div>
            </div>
        );
    }
}

render(<App/>, document.getElementById('app'));
