// templates/angular/demo/less/components/page-header/page-header.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'page-header',
  templateUrl: './page-header.component.html',
  styleUrls: ['./page-header.component.less']
})
export class PageHeaderComponent {
}

<div class="header-wrap">
  <header class="container">
    <div class="brand pull-left">Quick start</div>
    <div class="link pull-right">
      <a href="https://github.com/18616392776/quick-start-cli">Github</a>
    </div>
  </header>
</div>

// templates/react/javascript/demo/sass/components/page-header/page-header.jsx
import React from 'react';
import cssModules from 'react-css-modules';
import styles from './page-header.scss';

function pageHeader() {
  return (
    <div styleName="header-wrap">
      <header className="container">
        <div className="pull-left" styleName="brand">Quick start</div>
        <div className="pull-right" styleName="link">
          <a href="https://github.com/18616392776/quick-start-cli">Github</a>
        </div>
      </header>
    </div>
  );
}

export default cssModules(pageHeader, styles);
